# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173atNT8xhWZzPPjq6TjKp2uc18Huu4Wf
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

#Original x values
x = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)

#Add noise to y values
y = np.array([2, 4, 6, 8, 10]) + np.random.randint(-2, 3, size=5)

#PREDICTING THE MODEL
model = LinearRegression()
model.fit(x, y)
y_pred = model.predict(x)

#Plot noisy data and best-fit line
plt.scatter(x, y, color='blue', label='Noisy Data')
plt.plot(x, y_pred, color='red', label='Best Fit Line')
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Linear Regression with Noisy Data')
plt.legend()
plt.show()