# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173atNT8xhWZzPPjq6TjKp2uc18Huu4Wf
"""

#IMPORTING LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

#PREPARING THE DATA
x=np.array([1,2,3,4,5]).reshape(-1,1)
y=np.array([2,4,6,8,10])

#TRAIN THE MODEL
model=LinearRegression()
model.fit(x,y)

#PREDICT THE MODEL
y_pred=model.predict(x)

#PLOTTING THE RESULTS
plt.scatter(x,y,color='Blue')
plt.plot(x,y_pred,color='red')
plt.show()

