# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173atNT8xhWZzPPjq6TjKp2uc18Huu4Wf
"""

#IMPORTING THE LIBRARIES
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

#PREPARING THE DATA
x=np.array([1,2,3,4,5]).reshape(-1,1,)
y=np.array([2,4,6,8,10])

#MODEL TRAINING
model=LinearRegression()
model.fit(x,y)

#MAKING PREDICTTIONS MODELS
y_pred=model.predict(x)

#PLOTTING RESULTS
plt.scatter(x,y)
plt.plot(x,y_pred,color='red')
plt.show()

#ADDING THE INPUT VALUES
x_new=np.array([6,7,8,9,10]).reshape(-1,1)

#MAKING PREDICTIONS
y_new_pred=model.predict(x_new)
print("Predicted models:",y_new_pred)

#PLOTTING THE POINTS
plt.scatter(x,y,color='blue',label='Original data')
plt.plot(x,y_pred,color='Red',label='Line')
plt.scatter(x_new,y_new_pred,color='Green',label='Predictions')
plt.show()