# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

#Manually creating a data
data=pd.DataFrame({
      'Overs': [5, 10, 15, 5, 10, 15, 8, 12, 16, 20],
    'Runs': [50, 100, 150, 45, 95, 140, 70, 120, 180, 200],
    'Wickets': [2, 3, 4, 1, 2, 3, 2, 3, 4, 5],
    'Target': [180, 200, 220, 170, 195, 215, 190, 210, 230, 250]
})
print(data)

x=data[['Overs','Runs','Wickets']]
y=data[['Target']]

X_train,X_split,Y_train,Y_split=train_test_split(x,y,test_size=0.2, random_state=42)

#Training mode
model=LinearRegression()
model.fit(X_train,Y_train)

y_pred=model.predict(X_split)

plt.scatter(Y_split, y_pred, color='blue')
plt.xlabel("Actual Total Score")
plt.ylabel("Predicted Total Score")
plt.title("Actual vs Predicted Cricket Scores")
plt.show()