# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import zipfile
import pandas as pd

# Path to the zip file
zip_file_path = '/content/archive (4).zip'
# Directory to extract to
extract_dir = '.'

# Unzip the file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

# Now read the CSV file, assuming the extracted file is 'Virat_Kohli_100s - Virat_Kohli_100s.csv'
df = pd.read_csv('Virat_Kohli_100s - Virat_Kohli_100s.csv')

df.head()

df.tail()

#view the entire database
df

df.info()

df.describe()

#Used to view a particular data
virat_61=df.iloc[60]
print(virat_61)

#Used to view a particular data
virat_58=df.iloc[57]
print(virat_58)

#view the data from a particular point to another
df.iloc[21:46]

df[df.isnull().any(axis=1)]

df.isnull().sum()

